// ============================================================
// Portfolio Quest — ข้อมูลไทม์ไลน์จาก resume ของ Chakkrit Jansopanakul
// แหล่งข้อมูล: game-design-data.md (ตัดข้อมูลส่วนตัวที่ไม่ควรเผยแพร่ออกแล้ว)
// ============================================================

const GAME_INFO = {
  title: "Portfolio Quest",
  player: "Chakkrit Jansopanakul",
  role: "Vice President — ERP @ Bangkok Post · ผู้ก่อตั้ง บริษัท นาโนเดฟ จำกัด",
  province: "สมุทรปราการ ประเทศไทย",
  years: "2000 → ปัจจุบัน",
  totalSkills: 48,
  totalCerts: 5,
  finalStats: [
    "⏱️ 26 ปีในสายงาน IT / ERP",
    "🏢 8 องค์กร + บริษัทของตัวเอง 1 แห่ง",
    "🎓 2 ปริญญา + 1 หลักสูตร Non-Degree (NIDA)",
    "📜 5 หลักสูตรอบรม / ใบรับรอง",
    "✦ 48 ทักษะตลอดเส้นทาง",
    "🚀 ขึ้นระบบ ERP สำเร็จ 2 โครงการใหญ่ (Dynamics AX)",
    "🌏 ทำงานใน 2 ประเทศ (ไทย · เมียนมา)",
    "📚 เรียนควบคู่ทำงานครบทั้ง 3 ครั้ง — ไม่เคยหยุดเติมความรู้",
    "👔 จากลูกจ้างหน้าร้าน สู่ผู้บริหารและเจ้าของกิจการ",
  ],
};

// kind: uni | school | shop | factory | office | home | company | bridge
// badge: edu | work | both | bridge
const LEVELS = [
  {
    id: "rmutt",
    yearLabel: "2000–2002",
    place: "สถาบันเทคโนโลยีราชมงคล",
    role: "ป.ตรี เทคโนโลยีโทรคมนาคม · GPA 2.91",
    kind: "uni",
    badge: "edu",
    parallel: "เรียนควบคู่งานที่ IT Super Store",
    orgSize: 0,
    manages: 0,
    skills: ["Telecommunication", "Electronics", "Networking"],
    certs: [],
    palette: { sky: ["#7EC8E3", "#BDE3F0", "#FDF6E3"], accent: "#2E86AB" },
  },
  {
    id: "it-super-store",
    yearLabel: "2000–2002",
    place: "IT Super Store",
    role: "Customer Support",
    kind: "shop",
    badge: "work",
    parallel: "ทำงานควบคู่เรียน ป.ตรี",
    orgSize: 80,
    manages: 0,
    skills: ["Hardware Support", "Troubleshooting", "Customer Service"],
    certs: [],
    palette: { sky: ["#6FB7E9", "#A8D8F0", "#F5EFDC"], accent: "#E07A2F" },
  },
  {
    id: "military",
    yearLabel: "2002–2003",
    place: "รับราชการทหาร",
    role: "ฉากคั่น — เหตุผลที่ออกจาก IT Super Store",
    kind: "bridge",
    badge: "bridge",
    orgSize: 0,
    manages: 0,
    skills: [],
    certs: [],
    palette: { sky: ["#4A5240", "#7A8060", "#C9C29A"], accent: "#5B6142" },
  },
  {
    id: "school",
    yearLabel: "2003–2005",
    place: "โรงเรียนมัธยม (~160 คน)",
    role: "Help Desk Support · รายงานตรงต่อผู้อำนวยการ",
    kind: "school",
    badge: "work",
    orgSize: 160,
    manages: 0,
    skills: ["Help Desk", "Network Admin", "Programming Support"],
    certs: [],
    palette: { sky: ["#79C7E8", "#B5E0EE", "#EAF6DE"], accent: "#3A9D5D" },
  },
  {
    id: "flex-packaging",
    yearLabel: "2006–2010",
    place: "โรงงานบรรจุภัณฑ์ชนิดอ่อน (~200 คน)",
    role: "Application Developer & IT Support",
    kind: "factory",
    badge: "work",
    orgSize: 200,
    manages: 0,
    skills: ["ERP Support", "Windows Server", "Network Security", "BI Report", "IT Outsourcing"],
    certs: [
      "Advanced VB.NET Programming (2007)",
      "Oracle 9i Database Administration",
      "Oracle 10g Database Admin I & II",
    ],
    palette: { sky: ["#8FA5B8", "#C4CBD2", "#E8E0D2"], accent: "#7A6A56" },
  },
  {
    id: "mut",
    yearLabel: "2007–2009",
    place: "ม.เทคโนโลยีมหานคร",
    role: "M.Sc. Information Technology · GPA 3.47",
    kind: "uni",
    badge: "edu",
    parallel: "เรียนภาคค่ำ ควบคู่งานโรงงานบรรจุภัณฑ์",
    orgSize: 0,
    manages: 0,
    skills: ["Data Warehouse", "Data Mining", "OOP Design", "Database Administration", "SAP SOA"],
    certs: ["SAP SOA University Certificate (2008)", "ITEC6620 ERP Systems — SAP Thailand (2009)"],
    palette: { sky: ["#3B4A78", "#6C6FA8", "#E8B48A"], accent: "#8E6FC2" },
  },
  {
    id: "melamine",
    yearLabel: "2010 (4 เดือน)",
    place: "โรงงานเมลามีน (~4,600 คน)",
    role: "Database Administrator · องค์กรใหญ่ที่สุดในเส้นทาง",
    kind: "factory",
    badge: "work",
    orgSize: 4600,
    manages: 0,
    skills: ["IT Planning", "Web Application", "ISO 9000"],
    certs: [],
    palette: { sky: ["#9AA6B5", "#C0C8CF", "#DDD8CE"], accent: "#5E708A" },
  },
  {
    id: "packaging",
    yearLabel: "2010–2014",
    place: "โรงงานบรรจุภัณฑ์ (~500 คน)",
    role: "DBA & App Developer · รายงานตรงต่อ CEO · มีทีม 4 คน",
    kind: "factory",
    badge: "work",
    orgSize: 500,
    manages: 4,
    highlight: "ขึ้นระบบ ERP Dynamics AX 2009 ทั้งบริษัท",
    skills: ["Dynamics AX 2009", "SSIS / SSRS", "Data Center Tier", "CCTV & PABX", "IT SLA"],
    certs: [],
    palette: { sky: ["#7FA8C9", "#B3CBDD", "#EADFC8"], accent: "#2E6E9E" },
  },
  {
    id: "myanmar",
    yearLabel: "2015–2016",
    place: "โรงงานน้ำดื่ม ประเทศเมียนมา (~30 คน)",
    role: "General Manager · คุมโรงงานทั้งใบ · ทีม 28 คน",
    kind: "factory",
    badge: "work",
    abroad: true,
    orgSize: 30,
    manages: 28,
    highlight: "ออกจากสาย IT ไปบริหารโรงงานในต่างประเทศ",
    skills: ["Production Planning", "Factory Setup", "Machine Maintenance", "Team Training"],
    certs: [],
    palette: { sky: ["#E8A94A", "#F2C979", "#FAE7B5"], accent: "#C47B1E" },
  },
  {
    id: "bangkok-post",
    yearLabel: "2016–ปัจจุบัน",
    place: "Bangkok Post Public Co., Ltd (~600 คน)",
    role: "Vice President — ERP · รายงานตรงต่อ CFO · ทีม 4 คน",
    kind: "office",
    badge: "work",
    orgSize: 600,
    manages: 4,
    skills: ["Dynamics AX 2012 R2", "SSRS", "Dynamics CRM", "X++", "Team Leadership"],
    certs: [],
    palette: { sky: ["#101C33", "#2B3F63", "#6E7FA8"], accent: "#8FB4FF" },
  },
  {
    id: "nida",
    yearLabel: "2019",
    place: "NIDA — สถาบันบัณฑิตพัฒนบริหารศาสตร์",
    role: "Non-Degree ระดับปริญญาโท",
    kind: "uni",
    badge: "edu",
    parallel: "เรียนครั้งที่ 3 ระหว่างเป็น VP ที่ Bangkok Post",
    orgSize: 0,
    manages: 0,
    skills: ["Strategic Planning", "Public Administration"],
    certs: [],
    palette: { sky: ["#46528F", "#7C7FB5", "#E5A87C"], accent: "#B08968" },
  },
  {
    id: "freelance",
    yearLabel: "2024–2025",
    place: "งาน Freelance ที่ปรึกษา Odoo",
    role: "วางระบบ Odoo 11 / 15 / 16 / 19 ควบคู่งานประจำ",
    kind: "home",
    badge: "work",
    parallel: "ทำควบคู่ตำแหน่ง VP ที่ Bangkok Post",
    orgSize: 1,
    manages: 0,
    highlight: "ก้าวจาก ERP ค่าย Microsoft สู่ ERP โอเพนซอร์ส",
    skills: ["Odoo 11", "Odoo 15", "Odoo 16", "Odoo 19", "Odoo Implementation", "Client Management"],
    certs: [],
    palette: { sky: ["#2E3A5C", "#5C6690", "#D99A6C"], accent: "#875A7B" },
  },
  {
    id: "nanodev",
    yearLabel: "2026–ปัจจุบัน",
    place: "บริษัท นาโนเดฟ จำกัด",
    role: "ผู้ก่อตั้ง · Odoo Implementation",
    kind: "company",
    badge: "work",
    parallel: "ควบคู่ตำแหน่ง VP ที่ Bangkok Post",
    orgSize: 1,
    manages: 0,
    highlight: "ยกงาน Freelance สองปีขึ้นเป็นกิจการของตัวเอง",
    skills: ["Business Owner", "Odoo Consulting", "Project Delivery", "Client Relations"],
    certs: [],
    final: true,
    palette: { sky: ["#5BB7F0", "#A5DCF7", "#FFF6D9"], accent: "#1E88C9" },
  },
];
